### ISSUE TITLE
Help F-16 sidestick

### ISSUE THREAD

**Issue by gambiarra-eng** [schnoog/joystick_F16_sidestick#1]
Hello, Volker,how are you?
I hope you are well!
I am from Brazil!
I really liked your excellent project, please I have some questions, sorry for my questions, I don't have much knowledge of electronics!
I have 20Kg load cells, I have the HX 711, INA 122P, ADS 1115 16 bit i2c and the MCP23017, please what would the connections be like?
What would be the values to be implemented in tres Trimpots.
I had your PCB made at JLCPCB and I have already received them, please what are the values of resistors C1 and C2?
Thanks for any help!
gambiarra

**Comment by schnoog** [comment]
Hi gambiarra, thanks doing fine, hope you too.

C1 and C2 are only for some stabilisation. I used 0.1uF SMDs I had laying around. They aren't required for operation. 

In regards to the pots:

The one (Vref) should be tuned so that on A3 of the ADS1115 2.5V can be measured (or to be more explicit: Half the power supply voltage).

The other both define the amplification of the 2 axis. Therefore it's difficult to define an exact setting. 
How I have done it:

I placed my stick on a desk, attached a small thread on the higher part of it. On the other side of the thread I attached a 2kg weight (so that roughly 2kg were pulling on the joystick). Then I tuned the pot to have a full output signal (one direction to 0, the other to 32767) for both axis.

I really hope this help you. Please don't hesitate to ask if you have further questions.
